# Generated by Django 3.2.5 on 2021-07-18 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FleetFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FleetFacility',
                'verbose_name_plural': 'FleetFacilities',
            },
        ),
        migrations.CreateModel(
            name='FleetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FleetType',
                'verbose_name_plural': 'FleetTypes',
            },
        ),
        migrations.CreateModel(
            name='FleetRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_no', models.CharField(max_length=50)),
                ('layout', models.CharField(choices=[('11', '1-1'), ('12', '1-2'), ('21', '2-1'), ('22', '2-2')], max_length=2)),
                ('total_seat_no', models.IntegerField()),
                ('is_last_seat_available', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('route_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fleet_type', to='fleet_management.fleettype')),
            ],
            options={
                'verbose_name': 'FleetRegistration',
                'verbose_name_plural': 'FleetRegistrations',
            },
        ),
    ]
