# Generated by Django 3.2.5 on 2021-07-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FleetName',
                'verbose_name_plural': 'FleetNames',
            },
        ),
    ]
