# Generated by Django 3.2.5 on 2021-07-19 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0002_fleetname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fleetregistration',
            old_name='route_name',
            new_name='fleet_type',
        ),
        migrations.AddField(
            model_name='fleetregistration',
            name='fleet_facility',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fleet_facility', to='fleet_management.fleetfacility'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fleetregistration',
            name='fleet_name',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='FleetName', to='fleet_management.fleetname'),
            preserve_default=False,
        ),
    ]
