# Generated by Django 3.2.5 on 2021-07-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0003_auto_20210719_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleetregistration',
            name='seat_number',
            field=models.CharField(default='1', max_length=400),
            preserve_default=False,
        ),
    ]
