# Generated by Django 3.2.5 on 2021-07-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0004_fleetregistration_seat_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fleetregistration',
            old_name='model_no',
            new_name='coach_model',
        ),
        migrations.AddField(
            model_name='fleetregistration',
            name='coach_no',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fleetregistration',
            name='seat_number',
            field=models.CharField(help_text='Use comma to separate the input. Ex: A1 , A2 , A3 , A4 . . . ', max_length=400),
        ),
    ]
