# Generated by Django 3.2.5 on 2021-07-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0005_auto_20210719_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleetfacility',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
