# Generated by Django 3.2.5 on 2021-07-26 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0007_alter_fleetregistration_coach_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fleetfacility',
            options={'verbose_name': 'Fleet Facility', 'verbose_name_plural': 'Fleet Facilities'},
        ),
        migrations.AlterModelOptions(
            name='fleetname',
            options={'verbose_name': 'Fleet Name', 'verbose_name_plural': 'Fleet Names'},
        ),
        migrations.AlterModelOptions(
            name='fleetregistration',
            options={'verbose_name': 'Fleet Registration', 'verbose_name_plural': 'Fleet Registrations'},
        ),
        migrations.AlterModelOptions(
            name='fleettype',
            options={'verbose_name': 'Fleet Type', 'verbose_name_plural': 'Fleet Types'},
        ),
    ]
