# Generated by Django 3.2.5 on 2021-07-26 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0008_auto_20210726_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleetregistration',
            name='fleet_facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleet_facility', to='fleet_management.fleetfacility'),
        ),
        migrations.AlterField(
            model_name='fleetregistration',
            name='fleet_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FleetName', to='fleet_management.fleetname'),
        ),
        migrations.AlterField(
            model_name='fleetregistration',
            name='fleet_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleet_type', to='fleet_management.fleettype'),
        ),
    ]
