<<<<<<< HEAD
# Generated by Django 3.2.5 on 2021-07-17 10:44

from django.db import migrations, models
=======
# Generated by Django 3.2.5 on 2021-07-17 11:15

from django.db import migrations, models
import django.db.models.deletion
>>>>>>> cb5409d56bcb8665d7ace9f55e768f73a1274496


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
<<<<<<< HEAD
=======
                ('end_point', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='end_point', to='trip_management.location')),
                ('start_point', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='start_point', to='trip_management.location')),
>>>>>>> cb5409d56bcb8665d7ace9f55e768f73a1274496
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
            },
        ),
    ]
