# Generated by Django 3.2.5 on 2021-07-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='approximate_time',
            field=models.FloatField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='distance',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
