# Generated by Django 3.2.5 on 2021-07-17 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='end_point',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='end_point', to='trip_management.location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='start_point',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='start_point', to='trip_management.location'),
            preserve_default=False,
        ),
    ]
