# Generated by Django 3.2.5 on 2021-07-18 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip_management', '0002_auto_20210718_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripAssign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('route_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trip_route_name', to='trip_management.route')),
            ],
            options={
                'verbose_name': 'TripAssign',
                'verbose_name_plural': 'TripAssigns',
            },
        ),
    ]
