# Generated by Django 3.2.5 on 2021-07-18 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip_management', '0002_auto_20210717_1648'),
        ('trip_management', '0003_tripassign'),
    ]

    operations = [
    ]
