# Generated by Django 3.2.5 on 2021-07-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_management', '0006_alter_fleetfacility_details'),
        ('trip_management', '0006_alter_location_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripassign',
            name='fleet_name',
            field=models.ManyToManyField(to='fleet_management.FleetRegistration'),
        ),
    ]
