# Generated by Django 3.2.5 on 2021-07-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_management', '0008_tripdatetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tripassign',
            options={'verbose_name': 'Trip Assign', 'verbose_name_plural': 'Trip Assigns'},
        ),
        migrations.AlterModelOptions(
            name='tripdatetime',
            options={'verbose_name': 'Trip Date Time', 'verbose_name_plural': 'Trip Date Times'},
        ),
        migrations.RemoveField(
            model_name='tripassign',
            name='trip_date',
        ),
        migrations.AddField(
            model_name='tripassign',
            name='trip_date_time',
            field=models.ManyToManyField(to='trip_management.TripDateTime'),
        ),
    ]
