# Generated by Django 3.2.5 on 2021-07-26 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet_management', '0008_auto_20210726_0031'),
        ('trip_management', '0009_auto_20210720_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fleet_type', models.ManyToManyField(to='fleet_management.FleetType')),
                ('trip_route', models.ManyToManyField(to='trip_management.Route')),
            ],
            options={
                'verbose_name': 'Ticket Price',
                'verbose_name_plural': 'Ticket Prices',
            },
        ),
    ]
