# Generated by Django 3.2.5 on 2021-07-26 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip_management', '0009_auto_20210720_1950'),
        ('fleet_management', '0009_auto_20210726_1042'),
        ('ticket', '0002_auto_20210726_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketprice',
            name='fleet_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_fleet_type', to='fleet_management.fleettype'),
        ),
        migrations.RemoveField(
            model_name='ticketprice',
            name='trip_route',
        ),
        migrations.AddField(
            model_name='ticketprice',
            name='trip_route',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_trip_route', to='trip_management.route'),
            preserve_default=False,
        ),
    ]
